name: Setuo Vulkan
description: Setup Vulkan
inputs:
  version:
    description: Vulkan version
    required: false
    default: 1.3.290.0
runs:
  using: composite
  steps:
    - name: Install Vulkan SDK
      if: runner.os == 'Linux'
      shell: bash
      env:
        VULKAN_VERSION: "${{ inputs.version }}"
      run: |
        CODENAME=$(lsb_release -c | awk '{print $2}')
        APT_SOURCE_VERSION=$(echo $VULKAN_VERSION | sed 's/\.0$//')
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-$APT_SOURCE_VERSION-$CODENAME.list https://packages.lunarg.com/vulkan/$APT_SOURCE_VERSION/lunarg-vulkan-$APT_SOURCE_VERSION-$CODENAME.list
        sudo apt update -qq
        sudo apt install -y -qq vulkan-sdk
    - name: Install Vulkan SDK
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        VULKAN_VERSION: "${{ inputs.version }}"
      run: |
        $VulkanSDK = "D:\VulkanSDK\${Env:VULKAN_VERSION}"
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${Env:VULKAN_VERSION}/windows/VulkanSDK-${Env:VULKAN_VERSION}-Installer.exe" -OutFile VulkanSDK.exe
        .\VulkanSDK.exe --root $VulkanSDK --accept-licenses --default-answer --confirm-command install

        echo "VULKAN_SDK=$VulkanSDK" >> $env:GITHUB_ENV
        echo "$VulkanSDK/Bin" >> $env:GITHUB_PATH
