name: Setup premake
description: Setup premake
runs:
  using: composite
  steps:
    - name: Install premake
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
        tar xvzf premake-5.0.0-beta2-linux.tar.gz
        chmod +x premake5
        sudo mv premake5 /usr/local/bin/premake5
    - name: Install premake
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -OutFile premake.zip
        Expand-Archive -LiteralPath premake.zip -DestinationPath ../premake
        echo "${{ github.workspace }}/../premake" >> $env:GITHUB_PATH
