name: Setup compiler
description: Install MSVC for Windows and LLVM for Linux
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: pwsh
      run: |
        sudo apt-get update -qq
        sudo apt-get -y -qq install llvm-16 clang-16 clang-format-16 clang-tidy-16 lcov

        sudo update-alternatives --remove-all clang
        sudo update-alternatives --remove-all clang++

        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 0
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 0

        clang -v
        clang++ -v

        Write-Output "CC=clang" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "CXX=clang++" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1
