name: Main build

on:
  push:
    branches: [main]

jobs:
  build-release-windows:
    name: Build release (Windows)
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      VULKAN_VERSION: 1.3.250.1
    steps:
      - name: Setup premake
        run: |
          Invoke-WebRequest -Uri https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -OutFile premake.zip
          Expand-Archive -LiteralPath premake.zip -DestinationPath ../premake

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Vulkan SDK
        run: |
          $VulkanSDK = "D:\VulkanSDK\${Env:VULKAN_VERSION}"
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${Env:VULKAN_VERSION}/windows/VulkanSDK-${Env:VULKAN_VERSION}-Installer.exe" -OutFile VulkanSDK.exe
          .\VulkanSDK.exe --root $VulkanSDK --accept-licenses --default-answer --confirm-command install

          echo "VULKAN_SDK=$VulkanSDK" >> $env:GITHUB_ENV
          echo "$VulkanSDK/Bin" >> $env:GITHUB_PATH

      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: cache-vendor
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ runner.name }}-${{ hashFiles('./project.json') }}

      - name: Install dependencies and setup project
        run: |
          python3 project.py -m release 
          ../premake/premake5.exe vs2022

      - name: Build
        run: |
          msbuild .\workspace\QuollEngine.sln /p:configuration=Release /t:QuollEditor

      - name: Prepare archive
        run: |
          Compress-Archive -Path .\workspace\editor\bin\Release\* -DestinationPath QuollEngine.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: QuollEngine.zip
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          artifactContentType: "application/zip"
          name: "Experimental"
          tag: "experimental"
